### ISSUE TITLE
Line 71 in losul.xml (los21) is wrong

### ISSUE THREAD

**Issue by Professor-Berni** [LineageOS-UL/android#2]
The "name:" entry in [Line 71](https://github.com/LineageOS-UL/android/blob/53a4f05958aee3f031dc8a63e22bde74a7c269a8/snippets/losul.xml#L71) should be "LineageOS-UL/android_packages_modules_DeviceLock"; with underscores instead of slashes.

**Comment by Khalvat-M** [comment]
> The "name:" entry in [Line 71](https://github.com/LineageOS-UL/android/blob/53a4f05958aee3f031dc8a63e22bde74a7c269a8/snippets/losul.xml#L71) should be "LineageOS-UL/android_packages_modules_DeviceLock"; with underscores instead of slashes.

Thanks fixed
