### ISSUE TITLE
There is no packages/apps/Settings (any more?) in LineageOS-UL

### ISSUE THREAD

**Issue by Professor-Berni** [LineageOS-UL/android#3]
There is no packages/apps/Settings (any more?) in LineageOS-UL: [Klick](https://github.com/LineageOS-UL/android/blob/d8bb5514194050f68f0ae40aa86d347304eb9bb2/snippets/losul.xml#L86)

**Comment by Khalvat-M** [comment]
> There is no packages/apps/Settings (any more?) in LineageOS-UL: [Klick](https://github.com/LineageOS-UL/android/blob/d8bb5514194050f68f0ae40aa86d347304eb9bb2/snippets/losul.xml#L86)

Because we don't need it after qpr2 merge

**Comment by Professor-Berni** [comment]
Then it should be removed in the file losul.xml: [Klick](https://github.com/LineageOS-UL/android/blob/d8bb5514194050f68f0ae40aa86d347304eb9bb2/snippets/losul.xml#L86)

**Comment by Khalvat-M** [comment]
> Then it should be removed in the file losul.xml: [Klick](https://github.com/LineageOS-UL/android/blob/d8bb5514194050f68f0ae40aa86d347304eb9bb2/snippets/losul.xml#L86)

https://github.com/LineageOS-UL/android/commit/f901ae17779ce3d6c14269816cd7da8955e4c54b
